services:
  app:
    container_name: sapp
    build:
      # путь до докерфайла
      context: ./
      # докерфайл
      dockerfile: ServerDockerFile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=${DB_HOST}
      # - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - MIGRATIONS_PATH=file://./migrations
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - localnet
 
  db:
    image: postgres:17
    container_name: dbcont
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - localnet

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: a@e.com
      PGADMIN_DEFAULT_PASSWORD: admpass
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "8088:80"
    depends_on:
      - db
    networks:
      - localnet

volumes:
  postgres_data:
  pgadmin_data:


networks:
  localnet:
    driver: bridge
