auth_enabled: false

server:
  http_listen_address: localhost
  http_listen_port: 3100

common:
  path_prefix: /tmp/loki
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
  storage_config:
    filesystem:
      directory: /tmp/loki/data

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdbyshipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

chunk_store_config:
  max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: false
  retention_period: 0s