global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'alloy'
    static_configs:
      - targets: ['alloy:12345']
  
  - job_name: 'go_app'
    metrics_path: '/metrics' # Предполагаем, что ваше приложение экспортирует метрики
    static_configs:
      - targets: ['sapp:8080']
      